title: Abhishek Bhujang - Blog
email: abhishekbhujang2@gmail.com
url: "https://theabhishekbhujang.github.io"

usernames:
twitter: abhishekbhujan
instagram: theabhishekbhujang
linkedin: theabhishekbhujang
github: theabhishekbhujang

permalink: pretty

timezone: "+0530"
