# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abhishek Bhujang - Blog
email: abhishekbhujang2@gmail.com

description: Abhishek Bhujang - Security Researcher
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theabhishekbhujang.github.io" # the base hostname & protocol for your site
usernames:
  twitter: theabhibhujang
  github:  theabhishekbhujang
  linkedin: theabhishekbhujang
  instagram: theabhishekbhujang

permalink: pretty

# Build settings
markdown: kramdown
timezone: "+0530"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax:  false
      social:   true
